import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "packages/*/vitest.config.ts",
      "scripts/vitest.config.ts",
      "games/*/vitest*.config.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "./coverage",
      include: [
        "packages/*/src/**/*.ts",
        "packages/game-ui/src/**/*.svelte",
        "games/*/src/**/*.ts",
        "games/*/ui/**/*.{ts,svelte}",
        "games/*/bots/**/*.ts",
        "games/*/terminal/**/*.ts",
        "scripts/*.ts",
      ],
      exclude: [
        "**/node_modules/**",
        "**/dist/**",
        "**/tests/**",
        "**/*.d.ts",
        "**/vitest.config.*",
        "**/*.config.ts",
        "games/*/ui/main.ts",
        "packages/server/src/bun.ts",
        "games/*/server.ts",
        "games/*/bots/cli.ts",
        "games/*/terminal/demo.ts",
        "games/*/terminal/play.ts",
        "packages/launcher/src/runLauncher.ts",
        "games/*/launch.ts",
        "scripts/game.ts",
        "scripts/checkAgentsFilesCli.ts",
        "scripts/checkBoundariesCli.ts",
        "scripts/checkExportsCli.ts",
        "scripts/checkPathsCli.ts",
        "scripts/checkGatesCli.ts",
        "scripts/checkConventionsCli.ts",
        "packages/cli/src/cli.ts",
        "packages/cli/scripts/*.ts",
      ],
      thresholds: { lines: 100, functions: 100, branches: 100, statements: 100 },
    },
  },
});
